site_name: Kwery Documentation
site_favicon: favicon.ico
site_description: Documentation for Kwery, the easiest way to generate, schedule, view and email business reports from datasources using SQL
repo_name: Kwery 
repo_url: http://getkwery.com
google_analytics: ['UA-93051562-1', 'getkwery.com']
pages:
  - Home: index.md
